### ISSUE TITLE
about lumen extraction

### ISSUE THREAD

**Issue by wuzhuobin** [wuzhuobin/blood_vessel#33]
the function of lumen extracton has already re-coded to itk::ImageToImageFilter and vtkImageAlgorithm some things. But the algorithm itself may have some problems. 

Because the itk::ConfidenceConnectedImageFilter itself is quite depending on the seed point. 
The lumen itself should be homogeneous. if seed point some how was selected in an intensity is relatively larger than most of the vessel lumen's intensity, it will grow out of the vessel wall, isn't it?

solution?
smoothing? Gaussian filter, median filter, mean filter. open and close? 

And the itk::VotingBinaryIterativeHoleFillingImageFilter is quite rather time-comsuming, if wrong seed point  
is selected. Long time will be taken to iterate until whole image is filling up. 

and the filter itself is hard to keep growing when it meets the plaque, because that part's intensity is much higher than others. 

auto find seed points: local minima detection by gradient

about seed point: doing median filter on the radius r neighborhood voxels.

More testing should be continue. And maybe read some papers. whatever.

may be some weighting in Z-axis should work fine? since the carotid artery is vertical trend.

But it may not be the first priority. 

references by now:  a new hybrid algorithm based on watershed method, confidence connected Thresholding and region merging as preprossing for statistical classification of general medical images

**Comment by alabamagan** [comment]
Just so you know if you don't already do, current algorithm is based on confidence connection and the algorithm is followed by vote fill filter. 
Therefore there aren't anything we can do to prevent the region connecting to the external regions, we can only teach the user to reduce the parameter when they see that happens. 
Get Outlook for iOS

On Sat, Nov 19, 2016 at 9:27 PM +0800, "wuzhuobin" notifications@github.com wrote:

the function of lumen extracton has already re-coded to itk::ImageToImageFilter and vtkImageAlgorithm some things. But the algorithm itself may have some problems.

Because the itk::ConfidenceConnectedImageFilter itself is quite depending on the seed point.

The lumen itself should be homogeneous. if seed point some how was selected in an intensity is relatively larger than most of the vessel lumen's intensity, it will grow out of the vessel wall, isn't it?

solution?

smoothing? Gaussian filter, median filter, mean filter. open and close?

And the itk::VotingBinaryIterativeHoleFillingImageFilter is quite rather time-comsuming, if wrong seed point

is selected. Long time will be taken to iterate until whole image is filling up.

and the filter itself is hard to keep growing when it meets the plaque, because that part's intensity is much higher than others.

auto find seed points: local minima detection by gradient

about seed point: doing median filter on the radius r neighborhood voxels.

More testing should be continue. And maybe read some papers. whatever.

may be some weighting in Z-axis should work fine? since the carotid artery is vertical trend.

But it may not be the first priority.

references by now:  a new hybrid algorithm based on watershed method, confidence connected Thresholding and region merging as preprossing for statistical classification of general medical images

**Comment by alabamagan** [comment]
reference #42
